In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

QUESTION 1

In [2]:
import numpy as np

In [3]:
V = np.array([[1,-1,1],[1,2,4],[1,1,1]])

In [4]:
V

array([[ 1, -1,  1],
       [ 1,  2,  4],
       [ 1,  1,  1]])

In [5]:
inv = np.linalg.inv(V)
inv

array([[ 0.33333333, -0.33333333,  1.        ],
       [-0.5       ,  0.        ,  0.5       ],
       [ 0.16666667,  0.33333333, -0.5       ]])

In [6]:
f = np.array([[6],[9],[2]])
f

array([[6],
       [9],
       [2]])

In [7]:
np.dot(inv, f)

array([[ 1.],
       [-2.],
       [ 3.]])

QUESTION 2

In [8]:
matrix = np.array([[1,10],[1,15],[1,20],[1,25],[1,30],[1,35],[1,40],[1,45],[1,50],[1,55]], dtype=np.float64)

In [9]:
matrix[:,1] *= 10e-6
matrix

array([[1.0e+00, 1.0e-04],
       [1.0e+00, 1.5e-04],
       [1.0e+00, 2.0e-04],
       [1.0e+00, 2.5e-04],
       [1.0e+00, 3.0e-04],
       [1.0e+00, 3.5e-04],
       [1.0e+00, 4.0e-04],
       [1.0e+00, 4.5e-04],
       [1.0e+00, 5.0e-04],
       [1.0e+00, 5.5e-04]])

In [10]:
np.sqrt(matrix, where=[False, True],out=matrix)

array([[1.        , 0.01      ],
       [1.        , 0.01224745],
       [1.        , 0.01414214],
       [1.        , 0.01581139],
       [1.        , 0.01732051],
       [1.        , 0.01870829],
       [1.        , 0.02      ],
       [1.        , 0.0212132 ],
       [1.        , 0.02236068],
       [1.        , 0.02345208]])

In [11]:
inv = np.linalg.pinv(matrix)
inv

array([[ 8.38701801e-01,  6.18094756e-01,  4.32114414e-01,
         2.68262444e-01,  1.20128940e-01, -1.60938764e-02,
        -1.42886982e-01, -2.61973670e-01, -3.74608661e-01,
        -4.81739165e-01],
       [-4.21499372e+01, -2.95622150e+01, -1.89502743e+01,
        -9.60096678e+00, -1.14854673e+00,  6.62425569e+00,
         1.38590038e+01,  2.06540277e+01,  2.70809212e+01,
         3.31937316e+01]])

In [12]:
sigma = np.array([[65],[55.5],[52],[48],[46],[43],[42.5],[40.5],[40],[38]])
sigma

array([[65. ],
       [55.5],
       [52. ],
       [48. ],
       [46. ],
       [43. ],
       [42.5],
       [40.5],
       [40. ],
       [38. ]])

In [13]:
np.dot(inv,sigma)

array([[   79.0272523],
       [-1824.6052418]])